--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-04-06 11:57:24
with Com_N7space_Afechwas; use Com_N7space_Afechwas;
with Com_N7space_Hwas;     use Com_N7space_Hwas;
with Samv71afec_Dataview;  use Samv71afec_Dataview;
with Taste_Basictypes;     use Taste_Basictypes;
with adaasn1rtl;

package Hwas_RI is

   

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "hwas_check_queue";
end Hwas_RI;
