--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-04-06 11:07:03
with Com_N7space_Afechwas; use Com_N7space_Afechwas;
with Com_N7space_Hwas;     use Com_N7space_Hwas;
with Samv71afec_Dataview;  use Samv71afec_Dataview;
with Taste_Basictypes;     use Taste_Basictypes;
with adaasn1rtl;

package Manager_RI is

   procedure Afechwasinterface_Getvalue_Pi (Afec : in out asn1SccAfechwas; Analogchannel : in out asn1SccAfechwaschannel; Channeloutput : out asn1SccWord);
   
   
   procedure Afechwasinterface_Initinstance_Pi (Afec : out asn1SccAfechwas; Config : in out asn1SccAfechwasconfig);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "manager_check_queue";
end Manager_RI;
