/* Header file for function Manager in C language
 * Generated by TASTE on 2022-04-06 16:10:22
 * Context Parameters present : NO
 * Provided interfaces : GetTemperature
 * Required interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "manager.h"

// Function initialization - calls user startup code of all dependent functions
void init_manager(void);


/* Provided interfaces */
void manager_GetTemperature(void);


#ifdef __cplusplus
}
#endif

