/* ASN.1 System configuration file for function Manager
 * Generated by TASTE on 2022-04-06 16:10:22
 */

#define __NEED_AfecHwas_ACN
#define __NEED_AfecHwasChannel_ACN
#define __NEED_Word_ACN


#define __NEED_AfecHwas_ACN
#define __NEED_AfecHwasConfig_ACN
