/* Body file for function Manager
 * Generated by TASTE on 2022-04-06 16:10:22
 * Provided interfaces : GetTemperature
 * Required interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * User-defined properties for this function:
 * Timers              : 
 */
#include "manager_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
   extern long long getTimeInMilliseconds(void);
#endif




extern void init_afechwasdriver(void);
extern unsigned afechwasdriver_initialized;
extern void init_afechwasdriver(void);
extern unsigned afechwasdriver_initialized;
unsigned manager_initialized = 0;
void init_manager(void)
{
   if (0 == manager_initialized) {
      #ifdef __unix__
         // Initialize epoch for the MSC tracing in debug mode
         long long unused = getTimeInMilliseconds();
      #endif
      manager_initialized = 1;
      // Call user code startup function
      extern void manager_startup(void);
      manager_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == afechwasdriver_initialized) {
          init_afechwasdriver();
      }
      if (0 == afechwasdriver_initialized) {
          init_afechwasdriver();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Manager");
#endif
      manager_initialized = 2;
   }
}
void manager_GetTemperature()
{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: manager,gettemperature,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Directly call user code, no parameters to pass
   extern void manager_PI_GetTemperature(void);
   manager_PI_GetTemperature();
   // puts ("manager_gettemperature called");
}

