/* Body file for function Manager
 * Generated by TASTE on 2022-05-16 16:11:02
 * You can edit this file, it will not be overwritten
 * Provided interfaces : TfLunaReturnHwas_ErrorReadDataCmd_Ri, TfLunaReturnHwas_ReadDataCmd_Ri
 * Required interfaces : TfLunaHwas_InitTfLunaCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static bool initialized = false;

void manager_startup(void)
{
    Hal_console_usart_init();
}

void manager_PI_Init( void )
{
    if (!initialized)
    {
        manager_RI_TfLunaHwas_InitTfLunaCmd_Pi();

        initialized = true;
    }
    else
    {
    }    
}


void manager_PI_TfLunaReturnHwas_EchoCmd_Ri( const asn1SccByte * byte)
{
//    Hal_console_usart_write(byte, 1);
}

void manager_PI_TfLunaReturnHwas_ErrorReadDataCmd_Ri
      (const asn1SccTfLunaHwas_DataFrameErr *IN_err)

{
    uint8_t buffer[15];
    sprintf(buffer, "Error %i \n", *IN_err);
    Hal_console_usart_write(buffer, strlen(buffer));
    while(*IN_err == 2){};
}

void manager_PI_TfLunaReturnHwas_ErrorReadDataCmdComplex_Ri( const asn1SccTfLunaHwas_DataFrameErr * IN_err, const asn1SccTfLunaHwas_Data *IN_lidartflunadata, const asn1SccWord * ch1, const asn1SccByte *ch2 )
{
    uint8_t buffer[60];
    sprintf(buffer, "Error %i Dist %i Strength %i Temp %i ch1 %i ch2 %i\n", *IN_err,  IN_lidartflunadata->mDistance, IN_lidartflunadata->mStrength, IN_lidartflunadata->mTemp, *ch1, *ch2);
    Hal_console_usart_write(buffer, strlen(buffer));

}


void manager_PI_TfLunaReturnHwas_ReadDataCmd_Ri
      (const asn1SccTfLunaHwas_Data *IN_lidartflunadata)

{
    volatile static uint8_t buffer[40];
    sprintf(buffer, "D %lld S %lld T %lld\n", IN_lidartflunadata->mDistance, IN_lidartflunadata->mStrength, IN_lidartflunadata->mTemp);
    Hal_console_usart_write(buffer, strlen(buffer));
}


