
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-05-17 22:28:05
 * Context Parameters present : NO
 * Provided interfaces : Init, TfLunaReturnHwas_EchoCmd_Ri, TfLunaReturnHwas_ErrorReadDataCmdComplex_Ri, TfLunaReturnHwas_ErrorReadDataCmd_Ri, TfLunaReturnHwas_ReadDataCmd_Ri
 * Required interfaces : TfLunaHwas_InitTfLunaCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_Init( void );


void manager_PI_TfLunaReturnHwas_EchoCmd_Ri( const asn1SccByte * );


void manager_PI_TfLunaReturnHwas_ErrorReadDataCmdComplex_Ri( const asn1SccTfLunaHwas_DataFrameErr *, const asn1SccTfLunaHwas_Data *, const asn1SccWord *, const asn1SccByte * );


void manager_PI_TfLunaReturnHwas_ErrorReadDataCmd_Ri( const asn1SccTfLunaHwas_DataFrameErr * );


void manager_PI_TfLunaReturnHwas_ReadDataCmd_Ri( const asn1SccTfLunaHwas_Data * );

/* Required interfaces */
extern void manager_RI_TfLunaHwas_InitTfLunaCmd_Pi( void );


#ifdef __cplusplus
}
#endif
