/* Body file for function Manager
 * Generated by TASTE on 2022-05-16 16:11:02
 * You can edit this file, it will not be overwritten
 * Provided interfaces : TfLunaReturn_ErrorReadDataCmd_Ri, TfLunaReturn_ReadDataCmd_Ri
 * Required interfaces : TfLuna_InitTfLunaCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static bool initialized = false;

void manager_startup(void)
{
    Hal_console_usart_init();
}

void manager_PI_Init( void )
{
    if (!initialized)
    {
        manager_RI_TfLuna_InitTfLunaCmd_Pi();

        initialized = true;
    }
    else
    {
    }    
}

void manager_PI_TfLunaReturn_ErrorReadDataCmd_Ri
      (const asn1SccTfLuna_DataFrameErr *IN_err)

{
    uint8_t buffer[15];
    sprintf(buffer, "Error %i\n", *IN_err);
    Hal_console_usart_write(buffer, strlen(buffer));
    while(*IN_err == 2){};
}

void manager_PI_TfLunaReturn_ReadDataCmd_Ri
      (const asn1SccTfLuna_Data *IN_lidartflunadata)

{
    volatile static uint8_t buffer[40];
    sprintf(buffer, "D %lld S %lld T %lld\n", IN_lidartflunadata->mDistance, IN_lidartflunadata->mStrength, IN_lidartflunadata->mTemp);
    Hal_console_usart_write(buffer, strlen(buffer));
}


