
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-06-08 14:16:13
 * Context Parameters present : NO
 * Provided interfaces : Init, TfLunaReturn_ErrorReadDataCmd_Ri, TfLunaReturn_ReadDataCmd_Ri
 * Required interfaces : TfLuna_InitTfLunaCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_Init( void );


void manager_PI_TfLunaReturn_ErrorReadDataCmd_Ri( const asn1SccTfLuna_DataFrameErr * );


void manager_PI_TfLunaReturn_ReadDataCmd_Ri( const asn1SccTfLuna_Data * );

/* Required interfaces */
extern void manager_RI_TfLuna_InitTfLunaCmd_Pi( void );


#ifdef __cplusplus
}
#endif
