--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-03-28 17:53:21
with Com_N7space_Hwas;    use Com_N7space_Hwas;
with Com_N7space_Piohwas; use Com_N7space_Piohwas;
with Taste_Basictypes;    use Taste_Basictypes;
with Test3_Dataview;      use Test3_Dataview;
with adaasn1rtl;

package Hwas_RI is

   procedure Interruptsubscription_Interrupt_Ri (Inputparam : in out asn1SccInterrupt_Type);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "hwas_check_queue";
end Hwas_RI;
