/* Header file for function InterruptProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void interruptproxy_startup(void);

/* Provided interfaces */
void interruptproxy_PI_InterruptSubscription_Interrupt_Ri( const asn1SccInterruptNumber * );

/* Required interfaces */
extern void interruptproxy_RI_InterruptSubscription_Interrupt_Pi_Afec( const asn1SccInterruptNumber * );


extern void interruptproxy_RI_InterruptSubscription_Interrupt_Pi_Uart( const asn1SccInterruptNumber * );


#ifdef __cplusplus
}
#endif
