/* Body file for function InterruptProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "interruptproxy.h"

void interruptproxy_startup(void)
{

}

void interruptproxy_PI_InterruptSubscription_Interrupt_Ri
      (const asn1SccInterruptNumber *IN_interrupt)

{
   if(*IN_interrupt >= Nvic_Irq_Uart0 && *IN_interrupt <= Nvic_Irq_Uart4) {
       interruptproxy_RI_InterruptSubscription_Interrupt_Pi_Uart(IN_interrupt);
   }
   if(*IN_interrupt >= Nvic_Irq_Afec0 && *IN_interrupt <= Nvic_Irq_Afec1) {
       interruptproxy_RI_InterruptSubscription_Interrupt_Pi_Afec(IN_interrupt);
   }
}


