/* ASN.1 System configuration file for function HWAS
 * Generated by TASTE on 2022-04-06 16:10:22
 */
#define __NEED_SourceAddress_ACN
#define __NEED_WordMask_ACN
#define __NEED_Word_ACN


#define __NEED_DestinationAddress_ACN
#define __NEED_WordMask_ACN
#define __NEED_Word_ACN

