/* Header file for function HWAS in C language
 * Generated by TASTE on 2022-04-06 16:10:22
 * Context Parameters present : NO
 * Provided interfaces : RawMemoryAccess_ReadWord_Pi, RawMemoryAccess_WriteWord_Pi
 * Required interfaces : 
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "hwas.h"

// Function initialization - calls user startup code of all dependent functions
void init_hwas(void);


/* Provided interfaces */
void hwas_RawMemoryAccess_ReadWord_Pi
      (const char *IN_address, size_t IN_address_len,
       const char *IN_mask, size_t IN_mask_len,
       char *OUT_outputvalue, size_t *OUT_outputvalue_len);



void hwas_RawMemoryAccess_WriteWord_Pi
      (const char *IN_address, size_t IN_address_len,
       const char *IN_mask, size_t IN_mask_len,
       const char *IN_inputvalue, size_t IN_inputvalue_len);


#ifdef __cplusplus
}
#endif

