/* Body file for function HWAS
 * Generated by TASTE on 2022-04-06 16:10:22
 * Provided interfaces : RawMemoryAccess_ReadWord_Pi, RawMemoryAccess_WriteWord_Pi
 * Required interfaces : 
 * User-defined properties for this function:
 * Timers              : 
 */
#include "hwas_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
   extern long long getTimeInMilliseconds(void);
#endif




unsigned hwas_initialized = 0;
void init_hwas(void)
{
   if (0 == hwas_initialized) {
      #ifdef __unix__
         // Initialize epoch for the MSC tracing in debug mode
         long long unused = getTimeInMilliseconds();
      #endif
      hwas_initialized = 1;
      // Call user code startup function
      extern void hwas_startup(void);
      hwas_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function HWAS");
#endif
      hwas_initialized = 2;
   }
}
void hwas_RawMemoryAccess_ReadWord_Pi
      (const char *IN_address, size_t IN_address_len,
       const char *IN_mask, size_t IN_mask_len,
       char *OUT_outputvalue, size_t *OUT_outputvalue_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: hwas,rawmemoryaccess_readword_pi,%lld\n", msc_time);
      fflush(stdout);
  }
#endif
   __attribute__((section(".sdramMemorySection")))
   static asn1SccSourceAddress IN_ADDRESS;
#ifdef __unix__
   asn1SccSourceAddress_Initialize(&IN_ADDRESS);
#endif

   if (0 != Decode_ACN_SourceAddress (&IN_ADDRESS, (void *)IN_address, IN_address_len)) {
      #ifdef __unix__
         puts("Error decoding SourceAddress in function HWAS_RawMemoryAccess_ReadWord_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccWordMask IN_MASK;
#ifdef __unix__
   asn1SccWordMask_Initialize(&IN_MASK);
#endif

   if (0 != Decode_ACN_WordMask (&IN_MASK, (void *)IN_mask, IN_mask_len)) {
      #ifdef __unix__
         puts("Error decoding WordMask in function HWAS_RawMemoryAccess_ReadWord_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccWord OUT_OUTPUTVALUE;
#ifdef __unix__
   asn1SccWord_Initialize(&OUT_OUTPUTVALUE);
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hwas_PI_RawMemoryAccess_ReadWord_Pi
      (const asn1SccSourceAddress *,
       const asn1SccWordMask *,
       asn1SccWord *);





   // Call user code
   hwas_PI_RawMemoryAccess_ReadWord_Pi (&IN_ADDRESS, &IN_MASK, &OUT_OUTPUTVALUE);

   *OUT_outputvalue_len = Encode_ACN_Word
      ((void *)OUT_outputvalue,
       asn1SccWord_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_OUTPUTVALUE);
}


void hwas_RawMemoryAccess_WriteWord_Pi
      (const char *IN_address, size_t IN_address_len,
       const char *IN_mask, size_t IN_mask_len,
       const char *IN_inputvalue, size_t IN_inputvalue_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: hwas,rawmemoryaccess_writeword_pi,%lld\n", msc_time);
      fflush(stdout);
  }
#endif
   __attribute__((section(".sdramMemorySection")))
   static asn1SccDestinationAddress IN_ADDRESS;
#ifdef __unix__
   asn1SccDestinationAddress_Initialize(&IN_ADDRESS);
#endif

   if (0 != Decode_ACN_DestinationAddress (&IN_ADDRESS, (void *)IN_address, IN_address_len)) {
      #ifdef __unix__
         puts("Error decoding DestinationAddress in function HWAS_RawMemoryAccess_WriteWord_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccWordMask IN_MASK;
#ifdef __unix__
   asn1SccWordMask_Initialize(&IN_MASK);
#endif

   if (0 != Decode_ACN_WordMask (&IN_MASK, (void *)IN_mask, IN_mask_len)) {
      #ifdef __unix__
         puts("Error decoding WordMask in function HWAS_RawMemoryAccess_WriteWord_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccWord IN_INPUTVALUE;
#ifdef __unix__
   asn1SccWord_Initialize(&IN_INPUTVALUE);
#endif

   if (0 != Decode_ACN_Word (&IN_INPUTVALUE, (void *)IN_inputvalue, IN_inputvalue_len)) {
      #ifdef __unix__
         puts("Error decoding Word in function HWAS_RawMemoryAccess_WriteWord_Pi");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hwas_PI_RawMemoryAccess_WriteWord_Pi
      (const asn1SccDestinationAddress *,
       const asn1SccWordMask *,
       const asn1SccWord *);





   // Call user code
   hwas_PI_RawMemoryAccess_WriteWord_Pi (&IN_ADDRESS, &IN_MASK, &IN_INPUTVALUE);

}

