/* Body file for function Manager
 * Generated by TASTE on 2022-05-10 14:26:27
 * You can edit this file, it will not be overwritten
 * Provided interfaces : SunSensor_ReadDataAsyncCmd_Ri
 * Required interfaces : SunSensor_InitSunSensorCmd_Pi, SunSensor_ReadDataAsyncCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static bool initialized = false;

void manager_startup(void)
{
    Hal_console_usart_init();
}


void manager_PI_SunSensorReturn_ReturnDataCmd_Ri( const asn1SccConversionData * data)
{
    // Write your code here
    uint8_t buffer[80];
    sprintf(buffer, "Vol %lld Chn %lld Ins %lld\n", data->mValue, data->mChNumber, data->mInstance);
    Hal_console_usart_write(buffer, strlen(buffer));
}

void manager_PI_GetLuminosity( void )
{
    if (!initialized)
    {
        asn1SccAfecHwasConfig config = {    .mAfecInstance = asn1SccafecHwas_Instance_Afec0,
                                            .mStartupTime = 3,
                                            .mPrescalerValue = 2};
        manager_RI_SunSensor_InitSunSensorCmd_Pi(&config);

        initialized = true;
    }
    else
    {
        manager_RI_SunSensor_RequestDataCmd_Pi();
    }
}
