
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-06-07 15:46:44
 * Context Parameters present : NO
 * Provided interfaces : GetLuminosity, SunSensorReturn_ReturnDataCmd_Ri
 * Required interfaces : SunSensor_InitSunSensorCmd_Pi, SunSensor_RequestDataCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_GetLuminosity( void );


void manager_PI_SunSensorReturn_ReturnDataCmd_Ri( const asn1SccConversionData * );

/* Required interfaces */
extern void manager_RI_SunSensor_InitSunSensorCmd_Pi( const asn1SccAfecHwasConfig * );


extern void manager_RI_SunSensor_RequestDataCmd_Pi( void );


#ifdef __cplusplus
}
#endif
