/* Body file for function Manager
 * Generated by TASTE on 2022-05-10 14:26:27
 * You can edit this file, it will not be overwritten
 * Provided interfaces : SunSensor_ReadDataAsyncCmd_Ri
 * Required interfaces : SunSensor_InitSunSensorCmd_Pi, SunSensor_ReadDataAsyncCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static bool initialized = false;

static asn1SccSunSensor afec;

void manager_startup(void)
{
    Hal_console_usart_init();
}


void manager_PI_SunSensorReturn_ReturnDataCmd_Ri( const asn1SccConversionData * data)
{
    uint8_t buffer[30];
    sprintf(buffer, "Vol %lld Chn %lld Ins %hd\n", data->mValue, data->mChNumber, data->mInstance);
    Hal_console_usart_write(buffer, strlen(buffer));
}

void manager_PI_GetLuminosity( void )
{
    if (!initialized)
    {
        asn1SccSunSensorConfig config = {   .mAfecConfig ={
                                                  .mAfecInstance = asn1SccafecHwas_Instance_Afec0,
                                                  .mStartupTime = 15,
                                                  .mPrescalerValue = 255,},
                                            .mChannel = 8,
                                        };
        manager_RI_SunSensor_InitSunSensorCmd_Pi(&config, &afec);

        initialized = true;
    }
    else
    {
        manager_RI_SunSensor_RequestDataCmd_Pi(&afec);
    }
}
