/* Body file for function Manager,
 *
 * Generated by TASTE on 2022-03-28 18:14:13
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Blink
 * Required interfaces : PioHwas_InitPin_Pi, PioHwas_ResetPin_Pi, PioHwas_SetPin_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"
//#include <stdio.h>

static bool initialized = false;

static asn1SccPioHwas pio;
static asn1SccPioHwasPinConfig config = {.mPortConfig = asn1SccpioHwas_Port_C,
                               .mPinConfig = 9,
                               .mDirectionConfig = asn1SccpioHwas_Direction_Output};
static asn1SccWord value;

void manager_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Manager] Startup");

}

void manager_PI_Blink(void)
{
   // Write your code here
    if(!initialized)
    {
        manager_RI_PioHwas_InitPin_Pi(&pio, &config);
        initialized = true;
    }else {
        manager_RI_PioHwas_GetPin_Pi(&pio, &value);
        if(value)
        {
            manager_RI_PioHwas_ResetPin_Pi(&pio);
        }else {
            manager_RI_PioHwas_SetPin_Pi(&pio);
        }
    }
}


