/* Body file for function HWAS
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "hwas.h"
//#include <stdio.h>


void hwas_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[HWAS] Startup");
}

void hwas_PI_InterruptManagement_DisableInterrupt_Pi
      (const asn1SccInterruptNumber *IN_interrupt)

{
   // Write your code here
}


void hwas_PI_InterruptManagement_EnableInterrupt_Pi
      (const asn1SccInterruptNumber *IN_interrupt)

{
   // Write your code here
}


void hwas_PI_InterruptSubscriptionManagement_SubscribeToInterrupt_Pi
      (const asn1SccInterruptNumber *IN_interrupt)

{
   // Write your code here
}


void hwas_PI_RawMemoryAccess_ReadWord_Pi
      (const asn1SccSourceAddress *IN_address,
       const asn1SccWordMask *IN_mask,
       asn1SccWord *OUT_outputvalue)

{
   // Write your code here
}


void hwas_PI_RawMemoryAccess_WriteWord_Pi
      (const asn1SccDestinationAddress *IN_address,
       const asn1SccWordMask *IN_mask,
       const asn1SccWord *IN_inputvalue)

{
   // Write your code here
}


