/* Header file for function SunSensorProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void sunsensorproxy_startup(void);

/* Provided interfaces */
void sunsensorproxy_PI_SunSensorReturn_ReturnDataCmd_In( const asn1SccConversionData * );

/* Required interfaces */
extern void sunsensorproxy_RI_SunSensorReturn_ReturnDataCmd_Out( const asn1SccConversionData * );


#ifdef __cplusplus
}
#endif
