/* Body file for function SunSensorProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "sunsensorproxy.h"


void sunsensorproxy_startup(void)
{

}

void sunsensorproxy_PI_SunSensorReturn_ReturnDataCmd_In
      (const asn1SccConversionData *IN_choutput)

{
   sunsensorproxy_RI_SunSensorReturn_ReturnDataCmd_Out(IN_choutput);
}


