-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-03-25 09:31:36

package body Piohwasdriver_RI is

   procedure Rawmemoryaccess_Readbuffer_Ri
      (Address : in out asn1SccSourceaddress;
       Buffer :     out asn1SccBytebuffer) is
      procedure C_Rawmemoryaccess_Readbuffer_Ri
         (Address : in out asn1SccSourceaddress;
          Buffer :     out asn1SccBytebuffer)
         with Import,
              Convention => C,
              Link_Name  => "piohwasdriver_RI_RawMemoryAccess_ReadBuffer_Ri";
   begin
         C_Rawmemoryaccess_Readbuffer_Ri (address, buffer);
   end Rawmemoryaccess_Readbuffer_Ri;
   
   
   
   procedure Rawmemoryaccess_Readword_Ri
      (Address : in out asn1SccSourceaddress;
       Mask : in    out asn1SccWordmask;
       Inputvalue : out asn1SccWord) is
      procedure C_Rawmemoryaccess_Readword_Ri
         (Address : in out asn1SccSourceaddress;
          Mask : in    out asn1SccWordmask;
          Inputvalue : out asn1SccWord)
         with Import,
              Convention => C,
              Link_Name  => "piohwasdriver_RI_RawMemoryAccess_ReadWord_Ri";
   begin
         C_Rawmemoryaccess_Readword_Ri (address, mask, inputValue);
   end Rawmemoryaccess_Readword_Ri;
   
   
   
   procedure Rawmemoryaccess_Writebuffer_Ri
      (Address : in out asn1SccDestinationaddress;
       Buffer : in  out asn1SccBytebuffer) is
      procedure C_Rawmemoryaccess_Writebuffer_Ri
         (Address : in out asn1SccDestinationaddress;
          Buffer : in  out asn1SccBytebuffer)
         with Import,
              Convention => C,
              Link_Name  => "piohwasdriver_RI_RawMemoryAccess_WriteBuffer_Ri";
   begin
         C_Rawmemoryaccess_Writebuffer_Ri (address, buffer);
   end Rawmemoryaccess_Writebuffer_Ri;
   
   
   
   procedure Rawmemoryaccess_Writeword_Ri
      (Address : in    out asn1SccDestinationaddress;
       Mask : in       out asn1SccWordmask;
       Inputvalue : in out asn1SccWord) is
      procedure C_Rawmemoryaccess_Writeword_Ri
         (Address : in    out asn1SccDestinationaddress;
          Mask : in       out asn1SccWordmask;
          Inputvalue : in out asn1SccWord)
         with Import,
              Convention => C,
              Link_Name  => "piohwasdriver_RI_RawMemoryAccess_WriteWord_Ri";
   begin
         C_Rawmemoryaccess_Writeword_Ri (address, mask, inputValue);
   end Rawmemoryaccess_Writeword_Ri;

end Piohwasdriver_RI;
