--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body PioHwasDriver_RI is
   procedure RawMemoryAccess_ReadBuffer_Ri (Address : in out asn1SccSourceAddress; Buffer : out asn1SccByteBuffer) is null;
   procedure RawMemoryAccess_ReadWord_Ri (Address : in out asn1SccSourceAddress; Mask : in out asn1SccWordMask; Value : out asn1SccWord) is null;
   procedure RawMemoryAccess_WriteBuffer_Ri (Address : in out asn1SccDestinationAddress; Buffer : in out asn1SccByteBuffer) is null;
   procedure RawMemoryAccess_WriteWord_Ri (Address : in out asn1SccDestinationAddress; Mask : in out asn1SccWordMask; Value : in out asn1SccWord) is null;
end PioHwasDriver_RI;