--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-03-25 09:31:35
with Com_N7space_Piohwas; use Com_N7space_Piohwas;
with Project3_Dataview;   use Project3_Dataview;
with Taste_Basictypes;    use Taste_Basictypes;
with adaasn1rtl;

package Piohwasdriver_RI is

   procedure Rawmemoryaccess_Readbuffer_Ri (Address : in out asn1SccSourceaddress; Buffer : out asn1SccBytebuffer);
   
   
   procedure Rawmemoryaccess_Readword_Ri (Address : in out asn1SccSourceaddress; Mask : in out asn1SccWordmask; Inputvalue : out asn1SccWord);
   
   
   procedure Rawmemoryaccess_Writebuffer_Ri (Address : in out asn1SccDestinationaddress; Buffer : in out asn1SccBytebuffer);
   
   
   procedure Rawmemoryaccess_Writeword_Ri (Address : in out asn1SccDestinationaddress; Mask : in out asn1SccWordmask; Inputvalue : in out asn1SccWord);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "piohwasdriver_check_queue";
end Piohwasdriver_RI;
