pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""COM_N7SPACE_PIOHWAS"" are referenced");
pragma Warnings (Off, "use clause for package ""COM_N7SPACE_PIOHWAS"" has no effect");
with COM_N7SPACE_PIOHWAS; use COM_N7SPACE_PIOHWAS;
pragma Warnings (On, "no entities of ""COM_N7SPACE_PIOHWAS"" are referenced");
pragma Warnings (On, "use clause for package ""COM_N7SPACE_PIOHWAS"" has no effect");



package Piohwasdriver_Datamodel with SPARK_Mode
is


subtype asn1SccPiohwasdriver_States_index_range is Integer range 0..1;
type asn1SccPiohwasdriver_States is (asn1Sccoff, asn1Sccidle) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccPiohwasdriver_States use
    (asn1Sccoff => 0, asn1Sccidle => 1);

function asn1SccPiohwasdriver_States_Equal(val1, val2 : asn1SccPiohwasdriver_States) return Boolean;

function asn1SccPiohwasdriver_States_Init return asn1SccPiohwasdriver_States;

ERR_PIOHWASDRIVER_STATES:constant Integer := 26; 
function asn1SccPiohwasdriver_States_IsConstraintValid(val : asn1SccPiohwasdriver_States) return adaasn1rtl.ASN1_RESULT;
-- asn1SccPiohwasdriver_Context --------------------------------------------

type asn1SccPiohwasdriver_Context is record 
    state : asn1SccPiohwasdriver_States;
    init_done : adaasn1rtl.Asn1Boolean;
    piovar : COM_N7SPACE_PIOHWAS.asn1SccPioHwas;
    configvar : COM_N7SPACE_PIOHWAS.asn1SccPioHwasPinConfig;
    pmcvar : COM_N7SPACE_PIOHWAS.asn1SccPmcHwas;
end record;


function asn1SccPiohwasdriver_Context_Equal(val1, val2 : asn1SccPiohwasdriver_Context) return Boolean;

function asn1SccPiohwasdriver_Context_Init return asn1SccPiohwasdriver_Context;

ERR_PIOHWASDRIVER_CONTEXT:constant Integer := 206; 
ERR_PIOHWASDRIVER_CONTEXT_STATE_2:constant Integer := 36; 
ERR_PIOHWASDRIVER_CONTEXT_INIT_DONE:constant Integer := 41; 
ERR_PIOHWASDRIVER_CONTEXT_PIOVAR_2:constant Integer := 126; 
ERR_PIOHWASDRIVER_CONTEXT_CONFIGVAR_2:constant Integer := 161; 
ERR_PIOHWASDRIVER_CONTEXT_PMCVAR_2:constant Integer := 201; 
function asn1SccPiohwasdriver_Context_IsConstraintValid(val : asn1SccPiohwasdriver_Context) return adaasn1rtl.ASN1_RESULT;
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide Piohwasdriver_Datamodel;


end Piohwasdriver_Datamodel;