
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-04-07 10:47:13
 * Context Parameters present : NO
 * Provided interfaces : GetTemperature
 * Required interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_GetTemperature( void );

/* Required interfaces */
extern void manager_RI_AfecHwasInterface_GetValue_Pi( const asn1SccAfecHwas *, const asn1SccAfecHwasChannel *, asn1SccWord * );


extern void manager_RI_AfecHwasInterface_InitInstance_Pi( asn1SccAfecHwas *, const asn1SccAfecHwasConfig * );


#ifdef __cplusplus
}
#endif
