/* Body file for function Manager
 * Generated by TASTE on 2022-06-13 17:07:48
 * You can edit this file, it will not be overwritten
 * Provided interfaces : AfecHwas_GetValueCmd_Ri
 * Required interfaces : AfecHwas_GetValueCmd_Pi, AfecHwas_InitInstance_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static asn1SccAfecHwas afec;
static asn1SccAfecHwasConfig config = {
    .mAfecInstance = asn1SccafecHwas_Instance_Afec0,
    .mStartupTime = 3,
    .mPrescalerValue= 10};

static bool initialized = false;
static int channel = 8;


void manager_startup(void)
{
    Hal_console_usart_init();
}

void manager_PI_GetValue(void)
{
    if(!initialized)
    {
        manager_RI_AfecHwas_InitInstance_Pi( &afec, &config );
        initialized = true;
    }else
    {
        asn1SccAfecHwasInterfaceType_GetValueCmd_Type data = {afec, channel};
        manager_RI_AfecHwas_GetValueCmd_Pi(&data);
    }
}

void manager_PI_AfecHwas_GetValueCmd_Ri
      (const asn1SccAfecHwasInterfaceType_GetValueCmd_TypeNotify *IN_inputparam)
{
    static uint8_t buffer[40];
    sprintf(buffer, "Instance %d val %lld ch %lld\n", 
      IN_inputparam->chOutput.mInstance, 
      IN_inputparam->chOutput.mValue,
      IN_inputparam->chOutput.mChNumber);
    Hal_console_usart_write(buffer, strlen(buffer));
}
