/* Body file for function Manager
 * Generated by TASTE on 2022-04-06 11:12:12
 * You can edit this file, it will not be overwritten
 * Provided interfaces : GetTemperature
 * Required interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * User-defined properties for this function:
 * Timers              :
 */

#include "manager.h"

#include <Hal.h>

#include <stdio.h>
#include <string.h>

static bool initialized = false;
static asn1SccAfecHwas afec = {};
static asn1SccAfecHwasConfig config = {.mAfecInstance = asn1SccafecHwas_Instance_Afec0, .mStartupTime = 10,.mPrescalerValue = 2};
static asn1SccWord tempRawValue = 0;
static asn1SccWord channelNumber = 8;

void manager_startup(void)
{
    Hal_console_usart_init();
}

void manager_PI_AfecHwas_GetValueCmd_Ri( const asn1SccGetValueCmd_Type1 * args)
{
    uint8_t buffer[30];
    sprintf(buffer, "Voltage %i Ch %i Instance %i\n", args->chOutput.mValue, args->chOutput.mChNumber, args->chOutput.mInstance);
    Hal_console_usart_write(buffer, strlen(buffer));
}


void manager_PI_GetTemperature(void)
{
   // Write your code here
    if(!initialized)
    {
        manager_RI_AfecHwas_InitInstance_Pi(&afec, &config);
        initialized = true;
    }else {
        asn1SccGetValueCmd_Type getValueArgs = {.afec = afec, .analogChannel = channelNumber};
        manager_RI_AfecHwas_GetValueCmd_Pi(&getValueArgs);
    }
}
