/* Header file for function AfecHwasDriver in SDL language
 * Generated by TASTE on 2022-04-06 16:10:22
 * Context Parameters present : NO
 * Provided interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * Required interfaces : RawMemoryAccess_ReadWord_Ri, RawMemoryAccess_WriteWord_Ri
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif


// Function initialization - calls user startup code of all dependent functions
void init_afechwasdriver(void);


/* Provided interfaces */
void afechwasdriver_AfecHwasInterface_GetValue_Pi
      (const char *IN_afec, size_t IN_afec_len,
       const char *IN_analogchannel, size_t IN_analogchannel_len,
       char *OUT_channeloutput, size_t *OUT_channeloutput_len);



void afechwasdriver_AfecHwasInterface_InitInstance_Pi
      (char *OUT_afec, size_t *OUT_afec_len,
       const char *IN_config, size_t IN_config_len);


#ifdef __cplusplus
}
#endif

