-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-04-06 16:10:22

package body Afechwasdriver_RI is

   procedure Rawmemoryaccess_Readword_Ri
      (Address : in  out asn1SccSourceaddress;
       Mask : in     out asn1SccWordmask;
       Outputvalue : out asn1SccWord) is
      procedure C_Rawmemoryaccess_Readword_Ri
         (Address : in  out asn1SccSourceaddress;
          Mask : in     out asn1SccWordmask;
          Outputvalue : out asn1SccWord)
         with Import,
              Convention => C,
              Link_Name  => "afechwasdriver_RI_RawMemoryAccess_ReadWord_Ri";
   begin
         C_Rawmemoryaccess_Readword_Ri (address, mask, outputValue);
   end Rawmemoryaccess_Readword_Ri;
   
   
   
   procedure Rawmemoryaccess_Writeword_Ri
      (Address : in    out asn1SccDestinationaddress;
       Mask : in       out asn1SccWordmask;
       Inputvalue : in out asn1SccWord) is
      procedure C_Rawmemoryaccess_Writeword_Ri
         (Address : in    out asn1SccDestinationaddress;
          Mask : in       out asn1SccWordmask;
          Inputvalue : in out asn1SccWord)
         with Import,
              Convention => C,
              Link_Name  => "afechwasdriver_RI_RawMemoryAccess_WriteWord_Ri";
   begin
         C_Rawmemoryaccess_Writeword_Ri (address, mask, inputValue);
   end Rawmemoryaccess_Writeword_Ri;

end Afechwasdriver_RI;
