/* Body file for function AfecHwasDriver
 * Generated by TASTE on 2022-04-06 16:10:22
 * Provided interfaces : AfecHwasInterface_GetValue_Pi, AfecHwasInterface_InitInstance_Pi
 * Required interfaces : RawMemoryAccess_ReadWord_Ri, RawMemoryAccess_WriteWord_Ri
 * User-defined properties for this function:
 * Timers              : 
 */
#include "afechwasdriver_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
   extern long long getTimeInMilliseconds(void);
#endif



extern void adainit(void);

extern void init_hwas(void);
extern unsigned hwas_initialized;
extern void init_hwas(void);
extern unsigned hwas_initialized;
unsigned afechwasdriver_initialized = 0;
void init_afechwasdriver(void)
{
   if (0 == afechwasdriver_initialized) {
      #ifdef __unix__
         // Initialize epoch for the MSC tracing in debug mode
         long long unused = getTimeInMilliseconds();
      #endif
      afechwasdriver_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == hwas_initialized) {
          init_hwas();
      }
      if (0 == hwas_initialized) {
          init_hwas();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function AfecHwasDriver");
#endif
      afechwasdriver_initialized = 2;
   }
}
void afechwasdriver_AfecHwasInterface_GetValue_Pi
      (const char *IN_afec, size_t IN_afec_len,
       const char *IN_analogchannel, size_t IN_analogchannel_len,
       char *OUT_channeloutput, size_t *OUT_channeloutput_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: afechwasdriver,afechwasinterface_getvalue_pi,%lld\n", msc_time);
      fflush(stdout);
  }
#endif
   __attribute__((section(".sdramMemorySection")))
   static asn1SccAfecHwas IN_AFEC;
#ifdef __unix__
   asn1SccAfecHwas_Initialize(&IN_AFEC);
#endif

   if (0 != Decode_ACN_AfecHwas (&IN_AFEC, (void *)IN_afec, IN_afec_len)) {
      #ifdef __unix__
         puts("Error decoding AfecHwas in function AfecHwasDriver_AfecHwasInterface_GetValue_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccAfecHwasChannel IN_ANALOGCHANNEL;
#ifdef __unix__
   asn1SccAfecHwasChannel_Initialize(&IN_ANALOGCHANNEL);
#endif

   if (0 != Decode_ACN_AfecHwasChannel (&IN_ANALOGCHANNEL, (void *)IN_analogchannel, IN_analogchannel_len)) {
      #ifdef __unix__
         puts("Error decoding AfecHwasChannel in function AfecHwasDriver_AfecHwasInterface_GetValue_Pi");
      #endif
      return;
   }
   __attribute__((section(".sdramMemorySection")))
   static asn1SccWord OUT_CHANNELOUTPUT;
#ifdef __unix__
   asn1SccWord_Initialize(&OUT_CHANNELOUTPUT);
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void afechwasdriver_PI_AfecHwasInterface_GetValue_Pi
      (const asn1SccAfecHwas *,
       const asn1SccAfecHwasChannel *,
       asn1SccWord *);





   // Call user code
   afechwasdriver_PI_AfecHwasInterface_GetValue_Pi (&IN_AFEC, &IN_ANALOGCHANNEL, &OUT_CHANNELOUTPUT);

   *OUT_channeloutput_len = Encode_ACN_Word
      ((void *)OUT_channeloutput,
       asn1SccWord_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_CHANNELOUTPUT);
#ifdef __unix__
   // trace the SDL state
   if (1 == innerMsc) {
      extern char *afechwasdriver_state(void);
      printf ("INNER_SDL_STATE: afechwasdriver,%s\n", afechwasdriver_state());
      fflush(stdout);
  }
#endif
}


void afechwasdriver_AfecHwasInterface_InitInstance_Pi
      (char *OUT_afec, size_t *OUT_afec_len,
       const char *IN_config, size_t IN_config_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: afechwasdriver,afechwasinterface_initinstance_pi,%lld\n", msc_time);
      fflush(stdout);
  }
#endif
   __attribute__((section(".sdramMemorySection")))
   static asn1SccAfecHwas OUT_AFEC;
#ifdef __unix__
   asn1SccAfecHwas_Initialize(&OUT_AFEC);
#endif
   __attribute__((section(".sdramMemorySection")))
   static asn1SccAfecHwasConfig IN_CONFIG;
#ifdef __unix__
   asn1SccAfecHwasConfig_Initialize(&IN_CONFIG);
#endif

   if (0 != Decode_ACN_AfecHwasConfig (&IN_CONFIG, (void *)IN_config, IN_config_len)) {
      #ifdef __unix__
         puts("Error decoding AfecHwasConfig in function AfecHwasDriver_AfecHwasInterface_InitInstance_Pi");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void afechwasdriver_PI_AfecHwasInterface_InitInstance_Pi
      (asn1SccAfecHwas *,
       const asn1SccAfecHwasConfig *);





   // Call user code
   afechwasdriver_PI_AfecHwasInterface_InitInstance_Pi (&OUT_AFEC, &IN_CONFIG);

   *OUT_afec_len = Encode_ACN_AfecHwas
      ((void *)OUT_afec,
       asn1SccAfecHwas_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_AFEC);
#ifdef __unix__
   // trace the SDL state
   if (1 == innerMsc) {
      extern char *afechwasdriver_state(void);
      printf ("INNER_SDL_STATE: afechwasdriver,%s\n", afechwasdriver_state());
      fflush(stdout);
  }
#endif
}

