/* Body file for function Manager
 * Generated by TASTE on 2022-05-24 16:05:35
 * You can edit this file, it will not be overwritten
 * Provided interfaces : ReadPinState
 * Required interfaces : PioHwas_GetPin_Pi, PioHwas_InitPin_Pi, PioHwas_ResetPin_Pi, PioHwas_SetPin_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>


static bool initialized = false;

asn1SccPioHwas endSwitchLeft;
asn1SccPioHwas endSwitchRight;

asn1SccPioHwasPinConfig endSwitchRightConfig = {.mPortConfig = asn1SccpioHwas_Port_A,
                       .mPinConfig = 6,
                       .mDirectionConfig = asn1SccpioHwas_Direction_Input,
                       .mControlConfig = asn1SccpioHwas_Control_Pio};
asn1SccPioHwasPinConfig endSwitchLeftConfig = {.mPortConfig = asn1SccpioHwas_Port_D,
                      .mPinConfig = 28,
                      .mDirectionConfig = asn1SccpioHwas_Direction_Input,
                      .mControlConfig = asn1SccpioHwas_Control_Pio};

bool leftState = false;
bool rightState = false;

void manager_startup(void)
{
   Hal_console_usart_init();
}

static inline void PrintEndSwitchName(asn1SccWord pinNumbe)
{
    if(pinNumbe == 0)
    {
        Hal_console_usart_write("Left ", 5);
    }else {
        Hal_console_usart_write("Right ", 6);
    }
}

static inline void CheckEndSwitchState(asn1SccPioHwas * const endSwitch, bool * oldState, asn1SccWord pinNumber)
{
    asn1SccWord state;
    manager_RI_PioHwas_GetPin_Pi(endSwitch, &state);

    if(state && *oldState != true)
    {
        PrintEndSwitchName(pinNumber);
        Hal_console_usart_write("End switch set\n", 15);
        *oldState = true;
    }else if((state == 0) && *oldState == true)
    {
        PrintEndSwitchName(pinNumber);
        Hal_console_usart_write("End switch reset\n", 17);
        *oldState = false;
    }
}

void manager_PI_ReadEndSwitchesState(void)
{
   if (!initialized)
   {
       initialized = true;
       manager_RI_PioHwas_InitPin_Pi(&endSwitchLeft, &endSwitchLeftConfig);
       manager_RI_PioHwas_InitPin_Pi(&endSwitchRight, &endSwitchRightConfig);
   }
   else
   {
       CheckEndSwitchState(&endSwitchLeft, &leftState, 0);
       CheckEndSwitchState(&endSwitchRight, &rightState, 1);
   }    
}


