/* Body file for function Manager
 * Generated by TASTE on 2022-05-23 19:41:13
 * You can edit this file, it will not be overwritten
 * Provided interfaces : 
 * Required interfaces : MP6500_InitMP6500Cmd_Pi, MP6500_SetDirectionLeftCmd_Pi, MP6500_SetDirectionRightCmd_Pi, MP6500_StepCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <string.h>

#include <Hal.h>

bool initialized = false;
bool dirChange = false;

asn1SccMP6500 mp6500;
asn1SccMP6500Config mp6500Config = {
    .mDirPioConfig = {.mPortConfig = asn1SccpioHwas_Port_C,
                       .mPinConfig = 19,
                       .mDirectionConfig = asn1SccpioHwas_Direction_Output,
                       .mControlConfig = asn1SccpioHwas_Control_Pio},
    .mStepPioConfig = {.mPortConfig = asn1SccpioHwas_Port_D,
                      .mPinConfig = 27,
                      .mDirectionConfig = asn1SccpioHwas_Direction_Output,
                      .mControlConfig = asn1SccpioHwas_Control_Pio},};
asn1SccMP6500Config dirConfig;


void manager_startup(void)
{
    Hal_console_usart_init();
}

void manager_PI_ChangeDir( void )
{
    if(dirChange)
    {
        dirChange = false;
        manager_RI_MP6500_SetDirectionLeftCmd_Pi(&mp6500);
    }else {
        dirChange = true;
        manager_RI_MP6500_SetDirectionRightCmd_Pi(&mp6500);
    }
}


void manager_PI_MakeStep( void )
{
    if (initialized)
    {
        manager_RI_MP6500_StepCmd_Pi(&mp6500);
    }else{
        manager_RI_MP6500_InitMP6500Cmd_Pi(&mp6500, &mp6500Config);
        initialized = true;
    }
}

