/* Body file for function Manager
 * Generated by TASTE on 2022-05-10 14:26:27
 * You can edit this file, it will not be overwritten
 * Provided interfaces : SunSensorHwas_ReadDataAsyncCmd_Ri
 * Required interfaces : SunSensorHwas_InitSunSensorCmd_Pi, SunSensorHwas_ReadDataAsyncCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"

#include <stdio.h>
#include <string.h>

#include <Hal.h>

static bool initialized = false;

void manager_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Manager] Startup");
    Hal_console_usart_init();
}


void manager_PI_SunSensorReturnHwas_ReturnDataCmd_Ri( const asn1SccConversionData * data)
{
    // Write your code here
    uint8_t buffer[30];
    sprintf(buffer, "Vol %i Chn %i Ins %i\n", data->mValue, data->mChNumber, data->mInstance);
    Hal_console_usart_write(buffer, strlen(buffer));
}

void manager_PI_GetLuminosity( void )
{
    if (!initialized)
    {
        asn1SccAfecHwasConfig conf;
        manager_RI_SunSensorHwas_InitSunSensorCmd_Pi(&conf);

        initialized = true;
    }
    else
    {
        asn1SccWord dummy;
        manager_RI_SunSensorHwas_RequestDataCmd_Pi(&dummy);
    }
}
