
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-05-11 12:09:40
 * Context Parameters present : NO
 * Provided interfaces : ReadData, SunSensorHwas_ReadDataAsyncCmd_Ri
 * Required interfaces : SunSensorHwas_InitSunSensorCmd_Pi, SunSensorHwas_ReadDataAsyncCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_ReadData( void );


void manager_PI_SunSensorHwas_ReadDataAsyncCmd_Ri( const asn1SccReadDataAsyncCmd_Type1 * );

/* Required interfaces */
extern void manager_RI_SunSensorHwas_InitSunSensorCmd_Pi( const asn1SccAfecHwasConfig * );


extern void manager_RI_SunSensorHwas_ReadDataAsyncCmd_Pi( const asn1SccReadDataAsyncCmd_Type * );


#ifdef __cplusplus
}
#endif
