
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-06-08 13:52:18
 * Context Parameters present : NO
 * Provided interfaces : Initialize, LidarTrigger_ReturnDataCmd_Ri, LidarTrigger_ReturnErrorCmd_Ri
 * Required interfaces : Lidar_InitLidarCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_Initialize( void );


void manager_PI_LidarTrigger_ReturnDataCmd_Ri( const asn1SccReturnDataCmd_Type * );


void manager_PI_LidarTrigger_ReturnErrorCmd_Ri( const asn1SccReturnErrorCmd_Type * );

/* Required interfaces */
extern void manager_RI_Lidar_InitLidarCmd_Pi( asn1SccLidar *, const asn1SccLidarConfig * );


#ifdef __cplusplus
}
#endif
