/* Body file for function Manager
 * Generated by TASTE on 2022-05-26 18:47:26
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Initialize, LidarTrigger_ReturnDataCmd_Ri, LidarTrigger_ReturnErrorCmd_Ri
 * Required interfaces : Lidar_CalibratedCmd_Pi, Lidar_InitLidarCmd_Pi, Lidar_StartScanningCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"
//#include <stdio.h>


void manager_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Manager] Startup");
}

void manager_PI_Initialize(void)
{
   // Write your code here
}


void manager_PI_LidarTrigger_ReturnDataCmd_Ri
      (const asn1SccReturnDataCmd_Type *IN_inputparam)

{
   // Write your code here
}


void manager_PI_LidarTrigger_ReturnErrorCmd_Ri
      (const asn1SccReturnErrorCmd_Type *IN_inputparam)

{
   // Write your code here
}


