/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 2 hk, tm
typedef enum {
   i_hk,
   i_tm
} T_egse_PI_list;

typedef enum {
   i_tc
} T_egse_RI_list;

