/* Body file for function ObjectDetector
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "objectdetector.h"
//#include <stdio.h>


void objectdetector_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[ObjectDetector] Startup");
}

void objectdetector_PI_LidarTrigger_ReturnDataCmd_Ri
      (const asn1SccLidarTriggerInterfaceType_ReturnDataCmd_Type *IN_inputparam)

{
   // Write your code here
}


void objectdetector_PI_LidarTrigger_ReturnErrorCmd_Ri
      (const asn1SccLidarTriggerInterfaceType_ReturnErrorCmd_Type *IN_inputparam)

{
   // Write your code here
}


