
/* Header file for function Manager in C language
 * Generated by TASTE on 2022-06-09 06:32:40
 * Context Parameters present : NO
 * Provided interfaces : Init
 * Required interfaces : Propulsion_ChangeStateCmd_Pi, Propulsion_InitPropulsionCmd_Pi
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void manager_startup(void);

/* Provided interfaces */
void manager_PI_Init( void );

/* Required interfaces */
extern void manager_RI_Propulsion_ChangeStateCmd_Pi( const asn1SccPropulsionThrusterIndex *, const asn1SccPropulsion_ThrusterState * );


extern void manager_RI_Propulsion_InitPropulsionCmd_Pi( asn1SccPropulsion *, const asn1SccPropulsionConfig * );


#ifdef __cplusplus
}
#endif
