/* Header file for function Manager
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void manager_startup(void);

/* Provided interfaces */
void manager_PI_Init( void );

/* Required interfaces */
extern void manager_RI_Propulsion_ChangeStateCmd_Pi( const asn1SccPropulsionThrusterIndex *, const asn1SccPropulsion_ThrusterState * );


extern void manager_RI_Propulsion_InitPropulsionCmd_Pi( asn1SccPropulsion *, const asn1SccPropulsionConfig * );


#ifdef __cplusplus
}
#endif
