// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT

#include "partition_1_timer_manager.h"

// When propulsiondriver_timer_Idle expires, this function is called:
extern void partition_1_timer_manager_RI_propulsiondriver_timer_Idle(void);

void partition_1_timer_manager_startup(void)
{
 // Timer start up (nothing to do)
}

void partition_1_timer_manager_PI_Tick(void)
{
   if (active == timers[propulsiondriver_timer_Idle].state && 0 == -- timers[propulsiondriver_timer_Idle].value) {
      partition_1_timer_manager_RI_propulsiondriver_timer_Idle();
      timers[propulsiondriver_timer_Idle].state = inactive;
   }

}

void partition_1_timer_manager_PI_SET_propulsiondriver_timer_Idle(asn1SccT_UInt32 *val)
{
   /* Timer value must be multiple of 10 ms */
   assert (0 == (*val % 10));
   timers[propulsiondriver_timer_Idle].state = active;
   timers[propulsiondriver_timer_Idle].value = *val / 10;
}

void partition_1_timer_manager_PI_RESET_propulsiondriver_timer_Idle(void)
{
   timers[propulsiondriver_timer_Idle].state = inactive;
}


