// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT
#pragma once
#include "dataview-uniq.h"
#include <assert.h>

typedef enum {
   propulsiondriver_timer_Idle
} partition_1_timer_manager_timers;

static struct {
   long long value;
   enum {inactive, active} state;
} timers[1] = {{ .value = 0, .state = inactive }};

void partition_1_timer_manager_startup(void);
void partition_1_timer_manager_PI_Tick(void);

void partition_1_timer_manager_PI_SET_propulsiondriver_timer_Idle(asn1SccT_UInt32 *val);
void partition_1_timer_manager_PI_RESET_propulsiondriver_timer_Idle(void);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
