/* Body file for function Manager
 * Generated by TASTE on 2022-04-15 17:49:28
 * You can edit this file, it will not be overwritten
 * Provided interfaces : UartHwas_ReadByteAsyncCmd_Ri, UartHwas_SendByteAsyncCmd_Ri
 * Required interfaces : UartHwas_InitUartCmd_Pi, UartHwas_ReadByteAsyncCmd_Pi, UartHwas_SendByteAsyncCmd_Pi
 * User-defined properties for this function:
 * Timers              : 
 */

#include "manager.h"
static bool wasInitialized = false;
static char * msg = {"Hello\n\r"};

static asn1SccUartHwas uart;
static asn1SccUartHwasConfig config = {.mInstance = asn1SccuartHwas_Instance_4, .mBaudrate = asn1SccuartHwas_Baudrate9600};

#define MSG_LEN 7
static int sentBytes = 0;

void manager_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Manager] Startup");
}

void manager_PI_SendData( void )
{
    if(!wasInitialized)
    {
        manager_RI_UartHwas_InitUartCmd_Pi(&uart, &config);
        wasInitialized = true;
    }
    else {
        sentBytes = 0;
        asn1SccSendByteAsyncCmd_Type sendByteStructure = {.uart = uart, .byteToSend = msg[sentBytes]};
        manager_RI_UartHwas_SendByteAsyncCmd_Pi(&sendByteStructure);
    }
}

void manager_PI_UartHwas_ReadByteAsyncCmd_Ri
      (const asn1SccReadByteAsyncCmd_Type1 *IN_inputparam)

{
   // Write your code here
}


void manager_PI_UartHwas_SendByteAsyncCmd_Ri
      (const asn1SccSendByteAsyncCmd_Type1 *IN_inputparam)

{
   // Write your code here
    sentBytes++;
    if(sentBytes < MSG_LEN)
    {
        asn1SccSendByteAsyncCmd_Type sendByteStructure = {.uart = uart, .byteToSend = msg[sentBytes]};
        manager_RI_UartHwas_SendByteAsyncCmd_Pi(&sendByteStructure);
    }else {
        sentBytes = 0;
    }
}


